language: python
cache: pip
python:
- '3.7'
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
install:
- pip install -r requirements_dev.txt
- python setup.py build_ext --inplace --force --define CYTHON_TRACE
- python setup.py install
script:
- pytest
after_success:
- coverage xml
- python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: arkottke
  password:
    secure: LTa4LnspJINiQGPvKMsxHK8pQHmS1NTHUqTCpPOUM5u+q+KjsmQQUVErNtibdmz+GCBd3Tl/EZjO7XB0+BODMJcquCuqXCS1plaLA70/X40lCDAVLDIKId3vRjc87f/yVXZTj2edjfvbzMortmMvUICyI1H+ttuc6YDpkk227IdL86Rdj7lXq0iiiElJPbrCccG1ku5O+QEtobVZVlrNBTNi479BUSagow+SGKw5e2QIrDkj799tEWYaa/7xekQBKu3/0wvSpJ6T7zq2GtnmZBaL8ipODnXPQcqVbFiSv92RSM1BmPojhZkGKQ3brRzqRKMNap4OmnisHr0b3nvDNVMA4m9t5Z5tYsH6jEML2XebUj0Ygxb3bpSDefwvn4QRCNJ/qWXfW3zu8pRmcgTxXoLNoeRKdVt8LHgeHFzM45tll2o57bb7pVvgkDe8wqDqKFlJ98XmFGUvnLNv28btZdHiykCaVqqgAFpDeek+K9WLlTBTGirC4qA7i4WgfBR3MvUcVIxAukSz6S5jvOTY8vF5T5/Hr/d1jtMrf8bPkx7FJMtIUw4KaDsoyGwMmM1z505nsmGJpQkC+LT3Jau0ujiRw+a8W5Zt1fhF85RBm8KeDqY7Xr/kogR1k40c8fRi5wr8a7La6b6HMehIEkFuHh3pJk5BO2oQV5TsdNueE+E=
  on:
    tags: true
    distributions: sdist
    repo: arkottke/cyl1tf
